name: 'Feature request'
about: 'Use this form to propose new features or enhancements.'
title: '[feature] '
labels: ['enhancement']
body:
  - type: textarea
    id: summary
    attributes:
      label: 'Summary'
      description: 'Short description of the proposed feature.'
      placeholder: 'A short, descriptive summary of the proposal.'
  - type: textarea
    id: problem
    attributes:
      label: 'Problem to solve'
      description: 'What problem does this feature solve? Who benefits?'
      placeholder: 'Describe the current limitation or pain point.'
  - type: textarea
    id: proposal
    attributes:
      label: 'Proposed solution'
      description: 'Describe the proposed implementation or API changes.'
      placeholder: 'Outline the change, including examples or pseudo-code.'
  - type: textarea
    id: alternatives
    attributes:
      label: 'Alternatives considered'
      description: 'Other approaches considered and why they were rejected.'
  - type: checkboxes
    id: checklist
    attributes:
      label: 'Checklist'
      options:
        - label: 'I considered backwards compatibility'
        - label: 'I considered security implications'
        - label: 'I added tests or a test plan'
